name: Bug Report
description: Report a potential bug in SARCOP Applications. 
title: "[BUG] -  "
labels: ["Bug"]
body:
  - type: dropdown
    id: esri-product
    validations:
      required: true
    attributes:
      label: Which app?
      multiple: false
      description: Select in which app you are observing this issue.
      options:
        - N/A
        - Survey123
        - QuickCapture
        - Field Maps
        - Dashboards
        - Intel Manager 1.0 (Web AppBuilder)
        - Intel Manager 2.0 (Experience Builder)
        - Other
  - type: textarea
    id: device
    attributes:
      label: Describe the Device, Operating System, and Browser
      description: A clear description of the device(s), operating system, and browser (if relevant)
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear description of the issue (optionally include before/after screenshots/GIFs).
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected instead, and why?
    validations:
      required: true
  - type: textarea
    id: sample
    attributes:
      label: Reproduction Steps & Sample
      description: |
        Provide clear, numbered steps to reproduce this bug with a sample app and data if needed. Recordings are also helpful. Make sure that web maps, web scenes, portal items, services and other resources used to reproduce this bug are accessible.
      placeholder: |
        Link to web map/app:
        1. Go to '...'
        2. Click on '...'
        3. ...
    validations:
      required: true
  - type: textarea
    id: relevant
    attributes:
      label: Other Relevant Info
      description: (e.g., Browser, OS, version, related issues, suggestions/resources on how to fix, etc.)
    validations:
      required: false
  - type: dropdown
    id: priority-impact
    validations:
      required: true
    attributes:
      label: Priority impact
      multiple: false
      description: What is the impact to you or your team? Use discretion and only select "need" or "emergency" priorities for high user impact and quality issues. For instance, would someone notice, in a bad way, if this issue were present in the release?
      options:
        - p0 - not time sensitive
        - p1 - time sensitive
        - p2 - emergency!
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does the issue effect your team or your work? Can range from minor to blocking or prohibiting workflows.
    validations:
      required: false
