name: Enhancement Request
description: Request an enhancement or a new feature in a product.
title: "[ENH] - "
labels: ["Enhancement"]
body:
  - type: dropdown
    id: esri-product
    validations:
      required: true
    attributes:
      label: Which app?
      multiple: false
      description: Select for which app you are requesting an enhancement.
      options:
        - N/A
        - QuickCapture
        - Field Maps
        - Dashboards
        - Intel Manager 1.0 (Web AppBuilder)
        - Intel Manager 2.0 (Experience Builder)
        - Other
  - type: textarea
    id: describe
    attributes:
      label: Describe requirements
      description: Description of what's missing and what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered using instead.
    validations:
      required: true
  - type: textarea
    id: relevant
    attributes:
      label: Other Relevant Info
      description: Add any other context or screenshots about the feature request.
    validations:
      required: false
  - type: dropdown
    id: priority-impact
    validations:
      required: true
    attributes:
      label: Priority impact
      multiple: false
      description: What is the impact to you or your team?
      options:
        - p0 - not time sensitive
        - p1 - time sensitive
        - p2 - emergency!
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does the issue effect your team or your work? Can range from minor to blocking or prohibiting workflows.
    validations:
      required: false
